[workspace]
members = [
    "interface",
    "server",
    "client",
    "client-tui",
    "tests", 
    "gen-docs",
    "client-ui/src-tauri"
]
resolver = "3"

[profile.dev.package."h-mail-client"]
opt-level = 3
