[package]
name = "gen-docs"
version = "0.1.0"
edition = "2024"

[dependencies]
schemars = "1.0.4"
serde = "1.0.219"
serde_json = "1.0.141"
h-mail-interface = { path="../interface", features = ["gen_docs"] }


[build-dependencies]
walkdir = "2.5.0"
itertools = "0.14.0"