[package]
name = "client-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
h-mail-client = { path="../client" }
tokio = { version = "1.46.1", features = ["fs", "rt", "rt-multi-thread", "macros"] }